import { useRouter } from 'next/router'
import styles from "../../styles/Home.module.css";
import Head from "next/head";

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps(context) {
    const id = context.params.id
    const response = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)
    const jsonData = await response.json();

    return {
        props: {
            post: jsonData,
        },
        // Next.js will attempt to re-generate the page:
        // - When a request comes in
        // - At most once every 10 seconds
        // revalidate: 10, // In seconds
    }
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// the path has not been generated.
export async function getStaticPaths() {
    const response = await fetch('https://jsonplaceholder.typicode.com/posts')
    const posts = await response.json();

    // Get the paths we want to pre-render based on posts
    const paths = posts.filter(x => x.id < 40).map((post) => ({
        params: { id: post.id.toString() }
    }))

    // We'll pre-render only these paths at build time.
    // { fallback: blocking } will server-render pages
    // on-demand if the path doesn't exist.
    return { paths, fallback: 'blocking' }
}

const Post = ({post}) => {

    const router = useRouter()
    const { pid } = router.query

    return (
        <div className={styles.container}>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">{post.title}</a>
                </h1>
                <div>

                </div>
            </main>
        </div>
                )
}

export default Post